Dashboard ui Design
ratnakn/cooperai-frontend-setup pull request #1
Opened 2022-11-24 13:01 UTC by AbhijitP98

2022-11-28 15:07 UTC, NaveenReliable requested changes

2022-11-28 15:07 UTC, NaveenReliable commented on src/components/molecules/DecisionCard/index.jsx
> +    ulist: {
use proper naming here for class name

2022-11-28 15:07 UTC, NaveenReliable commented on src/components/molecules/DecisionCard/index.jsx
> +                    <ul className={classes.ulist}>
Follow the same comments which is mentioned above.

2022-11-29 04:46 UTC, AbhijitP98 commented on src/components/molecules/DecisionCard/index.jsx
> +    ulist: {
In latest PR request this is fixed

2022-11-29 04:46 UTC, AbhijitP98 commented on src/components/molecules/DecisionCard/index.jsx
> +                    <ul className={classes.ulist}>
In latest PR request this is fixed ,so i'm closed this pr

2022-11-29 04:46 UTC, AbhijitP98 commented on src/components/molecules/DecisionCard/index.jsx
> +            {/* </Link> */}
In latest PR request this is fixed ,so i'm closed this pr

2022-11-29 07:45 UTC, merged