Decision api Intigration
ratnakn/cooperai-frontend-setup pull request #2
Opened 2022-11-28 12:24 UTC by AbhijitP98

2022-11-28 15:11 UTC, NaveenReliable requested changes

2022-11-28 15:11 UTC, NaveenReliable commented on src/components/molecules/DecisionCard/index.jsx
> +    ulist: {
Use Proper meaning full names for class names

2022-11-28 15:11 UTC, NaveenReliable commented on src/components/molecules/DecisionCard/index.jsx
> -                        }
Remove commented code

2022-11-28 15:11 UTC, NaveenReliable commented on src/components/molecules/DecisionCard/index.jsx
> -                        {data.remainDays} DAYS AGO
What is the issue here?

2022-11-28 15:11 UTC, NaveenReliable commented on src/utilities/DataRequest.js
> +                'Access-Control-Allow-Origin': '*',
Remove final comma mark as it is not required

2022-11-29 04:37 UTC, AbhijitP98 commented on src/components/molecules/DecisionCard/index.jsx
> +    ulist: {
updated with proper name

2022-11-29 04:38 UTC, AbhijitP98 commented on src/components/molecules/DecisionCard/index.jsx
> -                        }
removed commented codes

2022-11-29 04:38 UTC, AbhijitP98 commented on src/components/molecules/DecisionCard/index.jsx
> -                        {data.remainDays} DAYS AGO
This data not getting from api

2022-11-29 04:39 UTC, AbhijitP98 commented on src/utilities/DataRequest.js
> +                'Access-Control-Allow-Origin': '*',
removed comma

2022-11-29 07:45 UTC, merged