Logout Implimantation
ratnakn/cooperai-frontend-setup pull request #5
Opened 2022-12-05 13:19 UTC by AbhijitP98

2022-12-06 09:13 UTC, NaveenReliable requested changes

2022-12-06 09:13 UTC, NaveenReliable commented on src/sections/Header.js
> +import { useState } from 'react';
Keep imports in proper order as per airbnb standards.

2022-12-06 09:13 UTC, NaveenReliable commented on src/sections/Header.js
> +    const [logOutPopup,setLogOutPopup] = useState(false);
make this boolean name as confirmLogoutPopup

2022-12-06 09:31 UTC, AbhijitP98 commented on src/sections/Header.js
> +import { useState } from 'react';
Changed to proper imports.

2022-12-06 09:31 UTC, AbhijitP98 commented on src/sections/Header.js
> +    const [logOutPopup,setLogOutPopup] = useState(false);
Changed the name

2022-12-20 09:10 UTC, NaveenReliable approved these changes

2022-12-20 09:10 UTC, merged